### ISSUE TITLE
Some 2.4.13 bugs

### ISSUE THREAD

**Issue by rcentros** [trelby/trelby#60]
I feel like a "wet blanket," but I just wanted to pass on some bugs I've found in Trelby 2.4.13. From simplest to most complicated.

(I haven't tried the Debian (.deb) install or the Fedora repository install yet.)

The Git install has one (minor) bug (at least on my Linux computers). The manual.html file does not show up. Everything else seems to work fine. I just copied a manual.html file to the directory.

The Python install also has the lack of a manual.html file bug, plus it also doesn't put the name database or spellcheck file in the working directory. Easy to fix, just move these files to that directory (if they're available from another installation). 

The FlatPak install throws the same errors as the Python install (no manual.html file, no spellcheck file or name database — but in this case I can't figure out how to fix them because of where they're looking for these files (the name database and spellcheck) are supposed to be in this directory?

`/app/lib/python3.12/site-packages/trelby/names.txt.gz`

and...

`/app/lib/python3.12/site-packages/trelby/dict_en.dat.gz`

It appears it's looking for these files in the root directory? But I don't understand FlatPak's so this may be a "virtual root directory" inside the FlatPak? Anyhow I can't get this to work. (I think it was the same with 2.4.11 but I never tested these features before on the FlatPak version.)

But a bigger problem in the FlatPak install is that it won't find the PDF application. I don't know where it's trying to go, but when I put in /user/bin/atril (which is what I use — it doesn’t work with evince either) it goes nowhere. It returns this error "PDF viewer application not found." The Guess and Browse choices don't work here either and, as mentioned, manually inserting /user/bin/atril doesn't work.

Anyhow some bugs. Except for the FlatPak version fairly minor and easy to fix. I'm sorry I don't know how to fix the FlatPak issues (or even where to look -- I know FlatPak normally uses ~/.var and /var, but I don't see the files at the locations where it's looking for them.

One thing I would like to pass on (maybe a toggle could be installed at some point.) For those in North America, who use Letter sized paper, it's easy to make Trelby default to Letter.

Just go to config.py, search for "paper," and edit these two lines...

From...

   ```
# paper size
   v.addFloat("paperHeight", 297.0, "Paper/Height", 100.0, 1000.0)
   v.addFloat("paperWidth", 210.0, "Paper/Width", 50.0, 1000.0)
```

To...                

   ```
# paper size
   v.addFloat("paperHeight", 279.4, "Paper/Height", 100.0, 1000.0)
   v.addFloat("paperWidth", 215.9, "Paper/Width", 50.0, 1000.0)
```

From then on, when you open a new document it will default to Letter size instead of A4 (A4 is still available by choice).      

Anyhow, sorry to ramble. Thanks to everyone who is working on Trelby. Version 2.4.13 is about perfect. I always wanted to be able to toggle off the toolbar. (But now I’m so used to it that it will probably stay most of the time.)

Again, thanks!

**Comment by rcentros** [comment]
Now Using the GitHub version of 2.4.13. Everything works (except the **manual.html** file isn't found), but that's an extremely minor issue. The default configuration folder has been moved to ~/.config/trelby as planned. Very happy with 2.4.13.

I've found that, by using a small shell script in Debian-based versions of Linux to install via git, that I can bypass the make command and avoid the three or four hour wheel creation. Apparently Debian has a wheel built-in, it's just a matter of finding it. The Synaptic install process of the .deb file showed me requirements that were needed (four files, but the last two are apparently redundant). So this shell script has worked to install Trelby on Debian 11 and 12, Linux Mint 22 and 21.3, and Ubuntu 22.04. All without running make.

#!/bin/bash
sudo apt install libwxgtk-gl3.2-1t64
sudo apt install python3-wxgtk4.0
sudo apt install python3-lxml 
sudo apt install python3-reportlab
sudo apt install git
git clone https://github.com/trelby/trelby.git

Python3-lxml was needed in Debian and Ubuntu, apparently already installed in Linux Mint. For this to work in Ubuntu you have to add the Universal and source repositories (which are checked by default in the Live USB version of Ubuntu at least).

Once the script is run, you should be able to change into the trelby directory and run **python3 trelby.py**      

Not knowing exactly how to write .desktop files, I wrote this small shell script — Trelby(git) — and created a launcher using it (running in terminal was not checked in the app launcher, so no terminal in the background).

#! /bin/bash
cd ~/trelby
python3 trelby.py & 
exit

I'll continue testing this, but this appears to the most direct route (with newest changes) to using Trelby in Debian-based versions of Linux.

![image](https://github.com/user-attachments/assets/15ba73c1-ca7c-47c7-bccc-b13377c966b0)

(I have ~/jsscripts in the .bashrc Path which is why the Trelby(git) file is there. The "(git)" part of the name is there because I'm still experimenting with other Trelby installs.

**Comment by limburgher** [comment]
Thank you for the info!

So I've just corrected the manual.html issue and it will come out in 2.4.14.

Regarding PDF viewers, what Trelby's code does on Linux is to call xdg-open to open the user's default PDF viewer. If you leave the path blank in the Trelby flatpak config, and set your default in your desktop environment to atril or whatever, it should open that.

**Comment by rcentros** [comment]
> Regarding PDF viewers, what Trelby's code does on Linux is to call xdg-open to open the user's default PDF viewer. If you leave the path blank in the Trelby flatpak config, and set your default in your desktop environment to atril or whatever, it should open that.

Unfortunately I can't get this to work. If I leave it blank it wants me to add my settings. I put them in manually /usr/bin/atril (or evince or xpdf) it doesn't see them. When I browse for them in Trelby, I can go to /usr/bin and it will not show any of these three applications (even though they show up in the my file manager — Nemo — and when I type "which atril"). It's like Trelby is refusing to accept any of these three PDF viewers? (Should mention that Guess just tells me to enter my settings manually, probably because it can't "see" atril, evince or xpdf (which have always worked for me in Trelby).

Maybe if I tried the PDF viewer you use I could see if that would work?

**Comment by limburgher** [comment]
Try setting it to /usr/bin/xdg-open.

**Comment by rcentros** [comment]
In regards to the FlatPak version in Debian-based distributions... Still no luck with PDFs...

> Try setting it to /usr/bin/xdg-open.

I have done so. When I do this Trelby doesn't throw an error, it just does nothing. 

What's really weird, as mentioned in a previous post, Browse will _not_ show the PDF applications, even though they plainly show up in the the File Manager. It's like Browse is purposely filtering them out. If I put these applications' path in manually, I get the "can't be found" error.

**Comment by Ian2020** [comment]
> What's really weird, as mentioned in a previous post, Browse will not show the PDF applications, even though they plainly show up in the the File Manager. 

Flatpaks are isolated/sandboxed from the system so they cannot do more then they are permitted to. Permissions are usually kept to a minimum and reading files in system dirs is usually disabled. You can allow them to see more of your filesystem by overriding these permissions, flatseal is a GUI tool for this. I don't recommend this approach however for fixing your problem, only for temporary troubleshooting.

**Comment by rcentros** [comment]
> Flatpaks are isolated/sandboxed from the system so they cannot do more then they are permitted to. Permissions are usually kept to a minimum and reading files in system dirs is usually disabled. You can allow them to see more of your filesystem by overriding these permissions, flatseal is a GUI tool for this. I don't recommend this approach however for fixing your problem, only for temporary troubleshooting.

Okay. So it's kind of like the issue with the Snap version of Firefox not being able to read the manual since it's in a non-local user directory. Do you know of any way around this without using flatseal? Will putting a copy of your PDF application in the .local/bin directory work. A Trelby huge feature (in my view) is how well it works with any PDF application.

**Comment by rcentros** [comment]
> * flatpak override --user --filesystem=/tmp org.trelby.Trelby

That's what it took. Thanks! I guess this would be considered a workaround, but for the first time I could get the flathub version of Trelby completely working in Linux Mint.
